POST http://localhost:3001/api/invoices
Content-Type: application/json

{
    "clientName": "Cora Jade",
    "clientEmail": "cora@wwe.com",
    "streetName": "Washington Street",
    "city": "New Orleans",
    "postcode": 40022,
    "country": "USA",
    "projectDes": "Tattoo Design",
    "price": 500
}