POST http://localhost:3001/api/invoices
Content-Type: application/json

{
    "clientName": "Randi Orton",
    "clientEmail": "randiRKhai@wwe.com",
    "streetName": "Sim City",
    "city": "California",
    "postcode": 32010,
    "country": "USA",
    "projectDes": "Broserweight",
    "price": 1250
}