POST http://localhost:5000/api/invoices
Content-Type: application/json

{
    "clientName": "Riddle",
    "clientEmail": "riddle@wwe.com",
    "streetName": "Sin City",
    "city": "Ontario",
    "postcode": 11224,
    "country": "USA",
    "projectDes": "Powerpoint Template",
    "price": 350,
    "due": "2022-04-10"
}